[package]
name = "a_star"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.39.0"
pistoncore-glutin_window = "0.68.0"
piston2d-opengl_graphics = "0.77.0"
rand = "0.8.5"
num-traits = { version = "0.2" }
